import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import LoginBtn from "./LoginBtn"
import LogoutBtn from './LogoutBtn';
import {getServerSession} from 'next-auth'
import {authOptions} from "@/pages/api/auth/[...nextauth]"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="navbar"> 

  <Link href="/" className="logo">훈게시판</Link> 
  <Link href="/list">List</Link> 
  {(session? <span><LogoutBtn /></span> :
  <span><LoginBtn /> </span>)}
  
  <h4>
  {
    (session ? `${session.user.name} 님 환영합니다. `:null)
  }
  </h4>
  </div> 
  {children}
  </body>

    </html>
  )
}
